### PR TITLE
First release of botsing-maven plugin

### PR DESCRIPTION
**Pull request by luandrea**
I have added classes to execute botsing as a maven plugin

### CODE REVIEW

**Comment by pderakhshanfar** [comment]
@luandrea thank you for working on the maven plugin. Just 2 points:
1- It would be nice if you can write some tests for your code.
2- I can see in the [pom file of botsing-maven](https://github.com/STAMP-project/botsing/blob/1356c27f1cc7d69334ceb01316ecb41f07070f33/botsing-maven/pom.xml) that you declared the dependency versions in this pom file. As it mentioned in the [README](https://github.com/STAMP-project/botsing/blob/master/README.md) file, dependency version must be declared as a property in the parent [pom.xml](https://github.com/STAMP-project/botsing/blob/master/pom.xml) file using the following syntax:
```
<properties>
  ...
  <!-- Dependencies versions -->
  <!-- To ensure a proper management of dependencies, all versions have to be declared here -->
  <depdencendy-artifactId.version>1.1.1</depdencendy-artifactId.version>
  ...
</properties>
```

**Comment by luandrea** [comment]
Hi @pderakhshanfar,
it's not correct to pot my dependencies in the parent pom. In the parent pom there should go only the common dependencies.
I will add tests after you accept my pull request.

**Comment by luandrea** [comment]
Hi @pderakhshanfar,
it's not correct to pot my dependencies in the parent pom. In the parent pom there should go only the common dependencies.
I will add tests after you accept my pull request.

**Comment by luandrea** [comment]
Hi @pderakhshanfar,
it's not correct to pot my dependencies in the parent pom. In the parent pom there should go only the common dependencies.
I will add tests after you accept my pull request.

**Comment by luandrea** [comment]
Hi @pderakhshanfar,
it's not correct to pot my dependencies in the parent pom. In the parent pom there should go only the common dependencies.
I will add tests after you accept my pull request.

**Comment by pderakhshanfar** [comment]
Dear @luandrea,

You should not put the dependencies in the parent pom file. You should define a property in this file, and use it in the pom file of your sub-module. If we put the versions in the sub-modules pom files, it will be harder to change the version of dependency in the future. But, if we only define this property in the parent pom file and use that property in our child pom files, we need to change only that property for this purpose.

As an example, we define a property for declaring the version of EvoSuite (our dependency) [here](https://github.com/STAMP-project/botsing/blob/c775290dd66eec2e78d91876021815866db1e68c/pom.xml#L72), and use this property whenever that we want to add a dependency in a sub-module (for instance [here](https://github.com/STAMP-project/botsing/blob/c775290dd66eec2e78d91876021815866db1e68c/botsing-reproduction/pom.xml#L31)).

**Comment by pderakhshanfar** [comment]
Dear @luandrea,

You should not put the dependencies in the parent pom file. You should define a property in this file, and use it in the pom file of your sub-module. If we put the versions in the sub-modules pom files, it will be harder to change the version of dependency in the future. But, if we only define this property in the parent pom file and use that property in our child pom files, we need to change only that property for this purpose.

As an example, we define a property for declaring the version of EvoSuite (our dependency) [here](https://github.com/STAMP-project/botsing/blob/c775290dd66eec2e78d91876021815866db1e68c/pom.xml#L72), and use this property whenever that we want to add a dependency in a sub-module (for instance [here](https://github.com/STAMP-project/botsing/blob/c775290dd66eec2e78d91876021815866db1e68c/botsing-reproduction/pom.xml#L31)).

**Comment by pderakhshanfar** [comment]
Dear @luandrea,

You should not put the dependencies in the parent pom file. You should define a property in this file, and use it in the pom file of your sub-module. If we put the versions in the sub-modules pom files, it will be harder to change the version of dependency in the future. But, if we only define this property in the parent pom file and use that property in our child pom files, we need to change only that property for this purpose.

As an example, we define a property for declaring the version of EvoSuite (our dependency) [here](https://github.com/STAMP-project/botsing/blob/c775290dd66eec2e78d91876021815866db1e68c/pom.xml#L72), and use this property whenever that we want to add a dependency in a sub-module (for instance [here](https://github.com/STAMP-project/botsing/blob/c775290dd66eec2e78d91876021815866db1e68c/botsing-reproduction/pom.xml#L31)).

**Comment by pderakhshanfar** [comment]
Dear @luandrea,

You should not put the dependencies in the parent pom file. You should define a property in this file, and use it in the pom file of your sub-module. If we put the versions in the sub-modules pom files, it will be harder to change the version of dependency in the future. But, if we only define this property in the parent pom file and use that property in our child pom files, we need to change only that property for this purpose.

As an example, we define a property for declaring the version of EvoSuite (our dependency) [here](https://github.com/STAMP-project/botsing/blob/c775290dd66eec2e78d91876021815866db1e68c/pom.xml#L72), and use this property whenever that we want to add a dependency in a sub-module (for instance [here](https://github.com/STAMP-project/botsing/blob/c775290dd66eec2e78d91876021815866db1e68c/botsing-reproduction/pom.xml#L31)).

**Comment by pderakhshanfar** [comment]
@luandrea 
You have added a dependency to the parent pom file for checkstyle plugin in [here](https://github.com/STAMP-project/botsing/blob/adee6011a6779ae8ba5ad4725346c78efa906ea1/pom.xml#L231-L235). I assume , you added it because of the problem that you had with the logging. right? Is it still necessary to be there?

**Pull request merged**
