### PR TITLE
[WIP] Added a customised fitness function for ArrayIndexOutOfBoundsException

### PR DESCRIPTION
**Pull request by CoolTomatos**
The `ITFFForArrayIndex` is based on `IntegrationTestingFF` and uses array index info logged in EvoSuite to calculated an improved fitness value for `ArrayIndexOutOfBoundsException`.

See https://github.com/STAMP-project/evosuite/pull/1

### CODE REVIEW

**Comment by CoolTomatos** [comment]
TODO: 
- [ ] move all the instrumentation changes in __EvoSuite__ to __botsing__. There should only access level change in __EvoSuite__

**Comment by pderakhshanfar** [comment]
@CoolTomatos 
Can you please check why the build process is failed? We should make sure that the build process is passing before accepting the pull request.

**Comment by CoolTomatos** [comment]
@pderakhshanfar  
Log says it has something to do with `javafx` not found.
It's weird because `javafx` is only removed for jdk 11 or newer. And the CI is using jdk8.

**Comment by CoolTomatos** [comment]
@pderakhshanfar 
It is an issue with openjdk, see AdoptOpenJDK/openjdk-build#577.
I will remove the usage of `javafx.util.Pair`.

**Pull request merged**
